version: "3.7"
services:
  postgresql_container:
    env_file:
      - .env
    image: postgres:10.0-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data/
volumes:
  database-data:
